### ISSUE TITLE
Error: Plugin error ... can't use rollup in watch mode

### ISSUE THREAD

**Issue by JLee21** [graup/vanilla-extract-rollup-example#1]
Hi @graup !

First off, thanks for writing vanilla-extract rollup plugin a few weeks ago - huge help for my team.
I noticed that rollup can't be in `watch` mode if the rollup plugin vanilla-extract is used.
Below I have steps to reproduce the error.
Do you have any thoughts?

```
cd packages/ui
npx rollup -c -w
# go to packages/ui/src/foundation/index.ts (or any other component file)
# save the file
```

```
bundles src/index.ts → dist...
[!] (plugin vanilla-extract) Error: Plugin error - Unable to get file name for unknown file "3f979318".
Error: Plugin error - Unable to get file name for unknown file "3f979318".
    at error (/Users/jorlee/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Object.FileEmitter.getFileName (/Users/jorlee/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:15589:24)
    at /Users/jorlee/vanilla-extract-rollup-example/node_modules/@vanilla-extract/rollup-plugin/dist/vanilla-extract-rollup-plugin.cjs.dev.js:82:32
    at Array.reduce (<anonymous>)
    at Object.renderChunk (/Users/jorlee/vanilla-extract-rollup-example/node_modules/@vanilla-extract/rollup-plugin/dist/vanilla-extract-rollup-plugin.cjs.dev.js:80:31)
    at /Users/jorlee/vanilla-extract-rollup-example/node_modules/rollup/dist/shared/rollup.js:22834:37

bundles src/index.ts → dist...
created dist in 995ms

[2022-05-18 11:56:44] waiting for changes...
```

PS, when editting a `*.css.ts` file and then saving it, rollup in watch mode does not update or detect any change was made.

**Comment by graup** [comment]
Hi! Someone else already created an issue for that, I'll be looking into that soon. Thanks for mentioning the change detection, I'll check that too.

https://github.com/seek-oss/vanilla-extract/issues/691
